apiVersion: v1
kind: Service
metadata:
  name: loki-query-proxy-user
  labels:
    app: loki-query-proxy
    mode: user
    app.kubernetes.io/managed-by: maas-observability
    app.kubernetes.io/component: loki-proxy
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: loki-query-proxy
    mode: user
