---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: gateway-auth-policy
  namespace: openshift-ingress
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  rules:
    metadata:
      # Enriching identity metadata with a proper subscription tier based on user groups
      matchedTier:
        http:
          # TODO: network policy to limit access to this endpoint
          url: http://maas-api.maas-api.svc.cluster.local:8080/v1/tiers/lookup
          contentType: application/json
          method: POST
          body:
            expression: |-
              { "groups": auth.identity.user.groups }
        cache:
          key:
            selector: auth.identity.user.username
          ttl: 300
    authentication:
      service-accounts:
        kubernetesTokenReview:
          audiences:
            - https://kubernetes.default.svc  # For user tokens (oc whoami -t)
            - maas-default-gateway-sa         # For ServiceAccount tokens (automated clients)
        defaults:
          # token normalization - https://docs.kuadrant.io/1.2.x/authorino/docs/user-guides/token-normalization/
          # Handle both ServiceAccounts (system:serviceaccount:ns:name) and regular users (email)
          userid:
            expression: |
              auth.identity.user.username.startsWith("system:serviceaccount:") ? 
                auth.identity.user.username.split(":")[3] : 
                auth.identity.user.username.split("@")[0]
    authorization:
      tier-access:
        # Only apply KServe permission checks for model inference paths
        # Skip maas-api control plane (/maas-api/*, /v1/*)
        when:
          - selector: request.path
            operator: matches
            value: ^/(?!maas-api|v1)[^/]+/[^/]+/.*   # Matches /{namespace}/{model}/... but NOT /maas-api/* or /v1/*
        kubernetesSubjectAccessReview:
          user:
            expression: auth.identity.user.username
          authorizationGroups:
            expression: auth.identity.user.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            namespace:
              expression: |
                request.path.split("/")[1]
            name:
              expression: |
                request.path.split("/")[2]
            verb:
              value: post
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  expression: auth.identity.userid
                tier:
                  expression: auth.metadata.matchedTier["tier"]
