# ServiceMonitor for ALL KServe LLM models (vLLM, simulators, etc.)
# Scrapes vLLM metrics from LLMInferenceService workload pods
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kserve-llm-models
  namespace: llm
  labels:
    app.kubernetes.io/part-of: maas-observability
spec:
  endpoints:
    - interval: 30s
      targetPort: 8000
      path: /metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/part-of: llminferenceservice
  namespaceSelector:
    matchNames:
      - llm


