# ServiceMonitor for Authorino /server-metrics endpoint.
#
# Deployed by: scripts/install-observability.sh (conditional — skipped if Kuadrant already scrapes /server-metrics)
# Scraped by:  OpenShift user-workload Prometheus (openshift-user-workload-monitoring)
#
# This scrapes auth evaluation metrics (auth_server_authconfig_total,
# auth_server_authconfig_duration_seconds, auth_server_authconfig_response_status, etc.)
# that are NOT collected by the Kuadrant-provided authorino-operator-monitor
# (which only scrapes /metrics for controller-runtime stats).
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorino-server-metrics
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/part-of: maas-observability
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      authorino-resource: authorino
  endpoints:
    - port: http
      path: /server-metrics
      interval: 30s
      scrapeTimeout: 10s
