---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: maas-gateway-metrics
  namespace: openshift-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: maas-default-gateway
  metrics:
  - providers:
    - name: prometheus
