# SA token for Perses Loki datasource to authenticate to LokiStack gateway.
apiVersion: v1
kind: Secret
metadata:
  name: loki-secret
  namespace: opendatahub
  labels:
    app.kubernetes.io/managed-by: maas-observability
    app.kubernetes.io/component: perses
  annotations:
    kubernetes.io/service-account.name: perses-sa
type: kubernetes.io/service-account-token
