apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - otel-collector.yaml
  - otel-collector-rbac.yaml
  - tenancy-proxy-code.yaml
  - tenancy-proxy-rbac.yaml
  - tenancy-proxy.yaml
  - usage-logs-admin-dashboard.yaml
  - usage-logs-dashboard.yaml
