apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-query-proxy
  namespace: opendatahub
  labels:
    app: loki-query-proxy
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/component: loki-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-query-proxy-logs
  labels:
    app: loki-query-proxy
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/component: loki-proxy
rules:
- apiGroups:
  - ''
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-query-proxy-logging-view
  namespace: opendatahub
  labels:
    app: loki-query-proxy
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/component: loki-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-query-proxy-logs
subjects:
- kind: ServiceAccount
  name: loki-query-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-query-proxy-logging-view-custom
  namespace: opendatahub
  labels:
    app: loki-query-proxy
    app.kubernetes.io/component: loki-proxy
    app.kubernetes.io/managed-by: maas-controller
subjects:
  - kind: ServiceAccount
    name: loki-query-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-application-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-query-proxy-tokenreview
  labels:
    app: loki-query-proxy
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/component: loki-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-query-proxy-tokenreview
  labels:
    app: loki-query-proxy
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/component: loki-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-query-proxy-tokenreview
subjects:
- kind: ServiceAccount
  name: loki-query-proxy
  namespace: opendatahub
